---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность перелистывать страницы в списке товаров
  - На странице товара и в каталоге должны отображаться название, рейтинг, цена со скидкой и без нее
  - В корзине должна быть возможность оформления заказа
  - Оформление заказа должно переводить на страницу оплаты
  - Пользователь должен иметь возможность удалать отдельные товары из корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть сделан в виде SPA-приложения
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь не должен иметь возможность редактировать описание товара
  - При нажатии на название магазина в шапке сайта происходит перевод на главную страницу
  - Должен быть запрос на подтверждение правильности заказа при оформлении
  - При оформлении заказа должны оставляться контакты клиента (телефон и/или email) для дальнейшей связи по заказу
