---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Все поля сайта должны быть защищены от XSS
  - Все поля сайта должны проходить проверку на корректнось введенных данных (заказ с нулевым или отрицательным количеством товара или ценой)
  - Должен быть запрос на подтверждение правильности заказа при оформлении
  - При оформлении заказа должы оставляться контакты клиента (телефон и/или email) для дальнейшей связи по заказу
